text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "server:file_system_location"
    options: [ '-gpPrvz' ]
site:
  title: "Bioinformatics Survey"
  subtitle: ""
  favicon: false
  url: "http://bioinfsurvey.org"
  analytics_token: "UA-27218809-1"
  navigation:
author:
  url: "http://www.michaelbarton.me.uk"
  name: "Michael Barton"
google_fonts:
scripts:
  - "https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  - "/fancybox/javascript.js"
stylesheets:
  "/bootstrap/css/bootstrap.min.css": "screen,projection,print"
