text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "server:file_system_location"
    options: [ '-gpPrvz' ]
site:
  title: "Site title"
  subtitle: "Site subtitle"
  favicon: false
  url: "http://www.example.com"
  analytics_token: "token"
  navigation:
    nav1: 'www.example.com'
    nav2: 'www.example.com'
  feed: 'www.example.com'
author:
  url: "http://www.example.com"
  name: "author name"
google_fonts:
  Molengo:
    - "regular"
    - "bold"
    - "italic"
    - "bolditalic"
  Volkorn:
    - "regular"
    - "bold"
    - "italic"
    - "bolditalic"
  Nobile:
    - "regular"
    - "bold"
    - "italic"
    - "bolditalic"
scripts:
  - "https://www.google.com/jsapi?key=ABQIAAAAY-Po-vITSRs13yAER6R-vxSra3Sy8luTxRRrne7YP3mAkjpCARS9K_z0sLbKHzv2zlMNiYLq0UExIg"
  - "https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  - "/vendor/fancybox/javascript.js"
  - "/javascript/prettify.js"
stylesheets:
  "http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css": "screen,projection"
  "/stylesheets/stylesheet.css": "screen,projection"
